####################################
# error messages returned by eTaSL
####################################
uint32  SUCCESS = 0

# LoadTask errors
uint32 SYNTAX_ERROR = 1

# InitializeTask errors:
uint32 FEATUREVAR_DID_NOT_CONVERGE = 1000


# RunTask errors:
uint32 SOLVER_DID_NOT_CONVERGE = 2000

uint32 CANCELLED = 2

# error code returned
uint32  errorcode

# string given additional description of the error
string  description
